### ISSUE TITLE
退出登录后头像显示错误

### ISSUE THREAD

**Issue by limingth** [kevingzhang/welog#19]
Bug report：登录之后发的 blog 头像是正确的，退出之后，头像显示为默认头像

**Comment by limingth** [comment]
登录后
![image](https://cloud.githubusercontent.com/assets/1249369/6360872/5a511d80-bc32-11e4-9f04-8b82c26543e8.png)

退出登录后
![image](https://cloud.githubusercontent.com/assets/1249369/6360878/65b87952-bc32-11e4-9e17-846fdeff6b12.png)

**Comment by cooloney** [comment]
这个要改list这个template了吧。

**Comment by limingth** [comment]
这个我熟，我可以来改

**Comment by limingth** [comment]
问题找到了，login 之前，user 的数据里面没有 emails，login 之后就有了。 原因不知道是啥，估计是 accounts 的默认规则，是不是需要显式的 publish 一下 emails 这个 field？  @kevingzhang 

![image](https://cloud.githubusercontent.com/assets/1249369/6361142/7c39ad0c-bc34-11e4-957f-62855b2e260d.png)

**Comment by cooloney** [comment]
等我一下，我把lists.js改成了lists.coffee.等我push一下，你在我的上面改。

**Comment by cooloney** [comment]
我的push到了cooloney branch

https://github.com/kevingzhang/welog/commit/0b0c821fb5137baf539a05a33b5283de13702c23

**Comment by limingth** [comment]
我们改的文件不同，不影响。 我的已经 pull request 了

## 

李明 / maodou.io

2015-02-24 14:58 GMT-08:00 Bryan Wu notifications@github.com:

**Comment by cooloney** [comment]
Cool, 我准备把这个几个JS都改成coffee了，看着烦人。

**Comment by limingth** [comment]
修改在 [publish.js](https://github.com/kevingzhang/welog/commit/2c9efe50203e55fab2834116b094f49e2ba6c596) 文件里面，Posts 和 post 附带的 user 数据 field 缺少了 emails.   已经加进去了。
