### ISSUE TITLE
list page 里面, 每个 post 应该是全部可以点 , 而不是必须点 > 

### ISSUE THREAD

**Issue by kevingzhang** [kevingzhang/welog#4]

**Comment by cooloney** [comment]
我来搞定这个

**Comment by cooloney** [comment]
fixed at https://github.com/kevingzhang/welog/commit/533a71c851adfa0ea54928128ba88dda6ae9cc5d and https://github.com/kevingzhang/welog/commit/dc9af2c61d6ab660c094d3c6943b68267cb61b16
