### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by cooloney** [kevingzhang/welog#5]
W20150211-11:14:08.793(-8)? (STDERR) 
W20150211-11:14:08.794(-8)? (STDERR) /home/roc/.meteor/packages/meteor-tool/.1.0.40.14ecd4u++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150211-11:14:08.794(-8)? (STDERR)                        throw(ex);
W20150211-11:14:08.794(-8)? (STDERR)                              ^
W20150211-11:14:08.794(-8)? (STDERR) Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
W20150211-11:14:08.794(-8)? (STDERR)     at Object.Meteor.userId (packages/accounts-base/accounts_server.js:19:1)
W20150211-11:14:08.794(-8)? (STDERR)     at Object.Posts.attachSchema.SimpleSchema.authorId.autoValue (app/both/collections.js:36:21)
W20150211-11:14:08.795(-8)? (STDERR)     at Object.runAV (packages/aldeed:simple-schema/simple-schema.js:960:1)
W20150211-11:14:08.795(-8)? (STDERR)     at packages/aldeed:simple-schema/simple-schema.js:1061:1
W20150211-11:14:08.795(-8)? (STDERR)     at Array.forEach (native)
W20150211-11:14:08.795(-8)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
W20150211-11:14:08.795(-8)? (STDERR)     at packages/aldeed:simple-schema/simple-schema.js:1060:1
W20150211-11:14:08.795(-8)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20150211-11:14:08.795(-8)? (STDERR)     at [object Object].getAutoValues (packages/aldeed:simple-schema/simple-schema.js:1023:1)
W20150211-11:14:08.795(-8)? (STDERR)     at [object Object].SimpleSchema.clean (packages/aldeed:simple-schema/simple-schema.js:368:1)

我是用的最新代码。

**Comment by limingth** [comment]
我昨天在 commit 之前是可以用的啊，你 fetch 了我最新的 commit 吗？ 加了 avatar 的那个

**Comment by cooloney** [comment]
fixed at https://github.com/kevingzhang/welog/commit/9c00a2ae362cb8b52608d56074e87024bf902aa6

**Comment by limingth** [comment]
出去了一天，刚回来，看来问题解决了，COOL！

## 

李明 / maodou.io

2015-02-11 16:52 GMT-08:00 kevingzhang notifications@github.com:
