### ISSUE TITLE
lists: pass null to postView

### ISSUE THREAD

**Issue by cooloney** [kevingzhang/welog#8]
http://localhost:3000/postView/null

**Comment by cooloney** [comment]
I fixed it. https://github.com/kevingzhang/welog/commit/dc9af2c61d6ab660c094d3c6943b68267cb61b16

**Comment by kevingzhang** [comment]
Have you merged code into master?

**Comment by cooloney** [comment]
Yes, you merged my code to master
https://github.com/kevingzhang/welog/commit/dc9af2c61d6ab660c094d3c6943b68267cb61b16

We can close this issue.
